name: Java gradle CI
on: push
env:
  docker_username: ${{ github.actor }}
  docker_password: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: clone
        uses: actions/checkout@v3
      - name: build
        run: chmod -R +x ci && ./ci/build-app.sh
      - name: upload arifact
        uses: actions/upload-artifact@v3
        with:
          name: source
          path: .
  Test:
    needs: [Build]
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: download source
        uses: actions/download-artifact@v3
        with:
          name: source
          path: .
      - name: test
        run: chmod -R +x ci && ./ci/unit-test-app.sh
  Docker-image:
    needs: [Test]
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: download build
        uses: actions/download-artifact@v3
        with:
          name: source
          path: .
      - name: build docker
        run: chmod +x ci/build-docker.sh && ci/build-docker.sh
      - name: push docker
        run: chmod +x ci/push-docker.sh && ci/push-docker.sh
  Component-test:
    needs: [Docker-image]
    runs-on: ubuntu-latest
    steps:
      - name: download build
        uses: actions/download-artifact@v3
        with:
          name: source
          path: .
      - name: Execute component test
        run: chmod +x ci/component-test.sh && ci/component-test.sh
  Performance-test:
    needs: [Docker-image]
    runs-on: ubuntu-latest
    steps:
      - name: download build
        uses: actions/download-artifact@v3
        with:
          name: source
          path: .
      - name: Execute performance test
        run: chmod +x ci/performance-test.sh && ci/performance-test.sh