name: workflow
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: clone
        uses: actions/checkout@v3
      - name: build
        run: ./ci/build-app.sh
      - name: upload arifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-code
          path: .